const products = [
    {
        id: 1,
        name: "iPhone 12 PRO",
        desc: `6.1" screen`,
        price: 999,
        image: "https://github.com/OskarKuchta/PhoneParadise/blob/main/functions/photos/1-min.jpg?raw=true",
    },
    {
        id: 2,
        name: "iPhone 12",
        desc: `5.4" screen`,
        price: 699,
        image: "https://github.com/OskarKuchta/PhoneParadise/blob/main/functions/photos/2-min.jpg?raw=true",
    },
    {
        id: 3,
        name: "Galaxy S",
        desc: `6.5" screen`,
        price: 399,
        image: "https://github.com/OskarKuchta/PhoneParadise/blob/main/functions/photos/3-min.jpg?raw=true",
    },
    {
        id: 4,
        name: "Google Pixel 5",
        desc: `6.0" screen`,
        price: 299,
        image: "https://github.com/OskarKuchta/PhoneParadise/blob/main/functions/photos/4-min.jpg?raw=true",
    },
    {
        id: 5,
        name: "Samsung Galaxy Note 20",
        desc: `6.7" screen`,
        price: 589,
        image: "https://github.com/OskarKuchta/PhoneParadise/blob/main/functions/photos/5-min.jpg?raw=true",
    },
    {
        id: 6,
        name: "OnePlus 9 Pro",
        desc: `6.7" screen`,
        price: 379,
        image: "https://github.com/OskarKuchta/PhoneParadise/blob/main/functions/photos/6-min.jpg?raw=true",
    },
    {
        id: 7,
        name: "Xiaomi Mi 11",
        desc: `6.81" screen`,
        price: 799,
        image: "https://github.com/OskarKuchta/PhoneParadise/blob/main/functions/photos/7-min.jpg?raw=true",
    },
    {
        id: 8,
        name: "Sony Xperia 1 III",
        desc: `6.5" screen`,
        price: 495,
        image: "https://github.com/OskarKuchta/PhoneParadise/blob/main/functions/photos/8-min.jpg?raw=true",
    },
    {
        id: 9,
        name: "LG G8 ThinQ",
        desc: `6.1" screen`,
        price: 399,
        image: "https://github.com/OskarKuchta/PhoneParadise/blob/main/functions/photos/9-min.jpg?raw=true",
    },
    {
        id: 10,
        name: "OnePlus Nord",
        desc: `6.44" screen`,
        price: 399,
        image: "https://github.com/OskarKuchta/PhoneParadise/blob/main/functions/photos/10-min.jpg?raw=true",
    },
    {
        id: 11,
        name: "Xiaomi Poco X3",
        desc: `6.67" screen`,
        price: 249,
        image: "https://github.com/OskarKuchta/PhoneParadise/blob/main/functions/photos/11-min.jpg?raw=true",
    },
    {
        id: 12,
        name: "Google Pixel 4a",
        desc: `5.81" screen`,
        price: 349,
        image: "https://github.com/OskarKuchta/PhoneParadise/blob/main/functions/photos/12-min.jpg?raw=true",
    },
    {
        id: 13,
        name: "Sony Xperia 5 II",
        desc: `6.1" screen`,
        price: 949,
        image: "https://github.com/OskarKuchta/PhoneParadise/blob/main/functions/photos/13-min.jpg?raw=true",
    },
];

export default products;