const products = [
    {
        id: 1,
        name: "iPhone 12 PRO",
        desc: `6.1" screen` ,
        price: 999,
        image: "../backend/photos/1-min.jpg",
    },
    {
        id: 2,
        name: "iPhone 12",
        desc: `5.4" screen` ,
        price: 699,
        image: "../backend/photos/2-min.jpg",
    },
    {
        id: 3,
        name: "Galaxy S",
        desc: `6.5" screen` ,
        price: 399,
        image: "../backend/photos/3-min.jpg",
    },
    {
        id: 4,
        name: "Google Pixel 5",
        desc: `6.0" screen` ,
        price: 299,
        image: "../backend/photos/4-min.jpg",
    },
    {
        id: 5,
        name: "Samsung Galaxy Note 20",
        desc: `6.7" screen` ,
        price: 589,
        image: "../backend/photos/5-min.jpg",
    },
    {
        id: 6,
        name: "OnePlus 9 Pro",
        desc: `6.7" screen` ,
        price: 379,
        image: "../backend/photos/6-min.jpg",
    },
    {
        id: 7,
        name: "Xiaomi Mi 11",
        desc: `6.81" screen` ,
        price: 799,
        image: "../backend/photos/7-min.jpg",
    },
    {
        id: 8,
        name: "Sony Xperia 1 III",
        desc: `6.5" screen` ,
        price: 495,
        image: "../backend/photos/8-min.jpg",
    },
    {
        id: 9,
        name: "LG G8 ThinQ",
        desc: `6.1" screen` ,
        price: 399,
        image: "../backend/photos/9-min.jpg",
    },
    {
        id: 10,
        name: "OnePlus Nord",
        desc: `6.44" screen` ,
        price: 399,
        image: "../backend/photos/10-min.jpg",
    },
    {
        id: 11,
        name: "Xiaomi Poco X3",
        desc: `6.67" screen` ,
        price: 249,
        image: "../backend/photos/11-min.jpg",
    },
    {
        id: 12,
        name: "Google Pixel 4a",
        desc: `5.81" screen` ,
        price: 349,
        image: "../backend/photos/12-min.jpg",
    },
    {
        id: 13,
        name: "Sony Xperia 5 II",
        desc: `6.1" screen` ,
        price: 949,
        image: "../backend/photos/13-min.jpg",
    },
];

export default products;