const products = [
    {
        id: 1,
        name: "iPhone 12 PRO",
        desc: "6.1-inch display",
        price: 999,
        image: "../backend/photos/1.png",
    },
    {
        id: 2,
        name: "iPhone 12",
        desc: "5.4-inch display",
        price: 699,
        image: "../backend/photos/2.png",
    },
    {
        id: 3,
        name: "Galaxy S",
        desc: "6.5-inch display",
        price: 399,
        image: "../backend/photos/3.png",
    },
    {
        id: 4,
        name: "Google Pixel 5",
        desc: "6.0-inch display",
        price: 699,
        image: "../backend/photos/4.png",
    },
    {
        id: 5,
        name: "Samsung Galaxy Note 20",
        desc: "6.7-inch display",
        price: 999,
        image: "../backend/photos/5.png",
    },
    {
        id: 6,
        name: "OnePlus 9 Pro",
        desc: "6.7-inch display",
        price: 899,
        image: "../backend/photos/6.png",
    },
    {
        id: 7,
        name: "Xiaomi Mi 11",
        desc: "6.81-inch display",
        price: 799,
        image: "../backend/photos/7.png",
    },
    {
        id: 8,
        name: "Sony Xperia 1 III",
        desc: "6.5-inch display",
        price: 1299,
        image: "../backend/photos/8.png",
    },
    {
        id: 9,
        name: "LG G8 ThinQ",
        desc: "6.1-inch display",
        price: 399,
        image: "../backend/photos/9.png",
    },
    {
        id: 10,
        name: "OnePlus Nord",
        desc: "6.44-inch display",
        price: 399,
        image: "../backend/photos/10.png",
    },
    {
        id: 11,
        name: "Xiaomi Poco X3",
        desc: "6.67-inch display",
        price: 249,
        image: "../backend/photos/11.png",
    },
    {
        id: 12,
        name: "Google Pixel 4a",
        desc: "5.81-inch display",
        price: 349,
        image: "../backend/photos/12.png",
    },
    {
        id: 13,
        name: "Sony Xperia 5 II",
        desc: "6.1-inch display",
        price: 949,
        image: "../backend/photos/13.png",
    },
];

export default products;